export const allIncomes = [
  {
    id: "1",
    src: "/static/images/avatar/1.jpg",
    title: "Brunch this weekend?",
    subTitle: " Ali Connors",
    description: "I'll be in your neighborhood doing errands this…",
  },
  {
    id: "2",
    src: "/static/images/avatar/1.jpg",
    title: "Summer BBQ?",
    subTitle: "to Scott, Alex, Jennifer",
    description: "Wish I could come, but I'm out of town this…",
  },
  {
    id: "1",
    src: "/static/images/avatar/1.jpg",
    title: "Brunch this weekend?",
    subTitle: " Ali Connors",
    description: "I'll be in your neighborhood doing errands this…",
  },
  {
    id: "2",
    src: "/static/images/avatar/1.jpg",
    title: "Summer BBQ?",
    subTitle: "to Scott, Alex, Jennifer",
    description: "Wish I could come, but I'm out of town this…",
  },
  {
    id: "1",
    src: "/static/images/avatar/1.jpg",
    title: "Brunch this weekend?",
    subTitle: " Ali Connors",
    description: "I'll be in your neighborhood doing errands this…",
  },
  {
    id: "2",
    src: "/static/images/avatar/1.jpg",
    title: "Summer BBQ?",
    subTitle: "to Scott, Alex, Jennifer",
    description: "Wish I could come, but I'm out of town this…",
  },
  {
    id: "1",
    src: "/static/images/avatar/1.jpg",
    title: "Brunch this weekend?",
    subTitle: " Ali Connors",
    description: "I'll be in your neighborhood doing errands this…",
  },
  {
    id: "2",
    src: "/static/images/avatar/1.jpg",
    title: "Summer BBQ?",
    subTitle: "to Scott, Alex, Jennifer",
    description: "Wish I could come, but I'm out of town this…",
  },
   {
    id: "1",
    src: "/static/images/avatar/1.jpg",
    title: "Brunch this weekend?",
    subTitle: " Ali Connors",
    description: "I'll be in your neighborhood doing errands this…",
  },
  {
    id: "2",
    src: "/static/images/avatar/1.jpg",
    title: "Summer BBQ?",
    subTitle: "to Scott, Alex, Jennifer",
    description: "Wish I could come, but I'm out of town this…",
  },
];
